services:
  server:
    build:
      context: . # 모노레포 최상단을 기준으로 설정
      dockerfile: ./apps/server/Dockerfile # 서버 Dockerfile 경로
    container_name: QuiWe_Server
    ports:
      - '4000:4000' # 4000번 포트 매핑
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine
    container_name: QuiWe_DB
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
