services:
  server:
    build:
      context: . # 모노레포 최상단을 기준으로 설정
      dockerfile: ./apps/server/Dockerfile # 서버 Dockerfile 경로
    container_name: QuiWe_Server
    ports:
      - '4000:4000' # 4000번 포트 매핑
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ENVIRONMENT: ${ENVIRONMENT}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      HASH_ROUNDS: ${HASH_ROUNDS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_TOKEN: ${JWT_REFRESH_TOKEN}
      KAKAO_ID: ${KAKAO_ID}
      KAKAO_SECRET: ${KAKAO_SECRET}
      KAKAO_CALLBACK_URI: ${KAKAO_CALLBACK_URI}
      KAKAO_LOGOUT_URI: ${KAKAO_LOGOUT_URI}
      CLIENT_CALLBACK_URI: ${CLIENT_CALLBACK_URI}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine
    container_name: QuiWe_DB
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
