import Header from '@/components/Layout/Header';
import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import QueryProvider from '@/providers/query-provider';
import { AnswerStoreProvider } from '@/providers/userAnswer-store-provider';
import { ResultStoreProvider } from '@/providers/result-store-provider';
import { ExplanationVisibleStoreProvider } from '@/providers/explanationVisible-provider';
import { UserStoreProvider } from '@/providers/user-provider';
import { Toaster } from 'react-hot-toast';
import Footer from '@/components/Layout/Footer';
import LayoutWrapper from '@/components/Layout/LayoutWrapper';

export const metadata: Metadata = {
  title: 'QuiWe',
  description: 'Generated by create next app'
};

const pretendard = localFont({
  src: '../fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
  display: 'swap'
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className={`${pretendard.variable} font-pretendard`}>
      <body>
        <QueryProvider>
          <UserStoreProvider>
            <Toaster />
            <Header />
            <AnswerStoreProvider>
              <ResultStoreProvider>
                <ExplanationVisibleStoreProvider>
                  <LayoutWrapper>{children}</LayoutWrapper>
                </ExplanationVisibleStoreProvider>
              </ResultStoreProvider>
            </AnswerStoreProvider>
          </UserStoreProvider>
        </QueryProvider>
        <Footer />
      </body>
    </html>
  );
}
