import Header from '@/components/Header';
import './globals.css';
import type { Metadata } from 'next';
import QueryProvider from '@/providers/query-provider';
import { AnswerStoreProvider } from '@/providers/userAnswer-store-provider';
import localFont from 'next/font/local';

export const metadata: Metadata = {
  title: 'QuiWe',
  description: 'Generated by create next app'
};

const pretendard = localFont({
  src: '../fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
  display: 'swap'
});

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${pretendard.variable} font-pretendard`}>
      <body>
        <QueryProvider>
          <Header />
          <AnswerStoreProvider>{children}</AnswerStoreProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
