name: EC2 Deploy CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feat/#17

jobs:
  build-and-push-to-dockerhub:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub Repository Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # 3. Create .env file (로컬에 생성)
      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.POSTGRES_PORT }}" > .env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "HASH_ROUNDS=${{ secrets.HASH_ROUNDS }}" >> .env
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env

      # 4. Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -f ./apps/server/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/quiwe .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/quiwe

  upload-env-file:
    name: Upload .env File to EC2
    runs-on: ubuntu-latest
    needs: build-and-push-to-dockerhub

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload .env to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: '.env'
          target: '~/quiwe/.env'

  deploy-to-ec2:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: upload-env-file

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop quiwe || true
            sudo docker rm quiwe || true

            if sudo lsof -i :4000; then
               sudo kill -9 $(sudo lsof -t -i:4000) || true
            fi

            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/quiwe

            sudo docker run -d --name quiwe --env-file ~/quiwe/.env -p 4000:4000 ${{ secrets.DOCKERHUB_USERNAME }}/quiwe
