name: EC2 Deploy CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feat/#17

jobs:
  build-and-push-to-dockerhub:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub Repository Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # 3. Docker 이미지 빌드
      - name: Build Docker Image
        run: |
          docker build -f ./apps/server/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/quiwe .

      # 4. Docker 이미지 푸시
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/quiwe

  deploy-to-ec2:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build-and-push-to-dockerhub

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        # 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop quiwe || true

            if sudo lsof -i :4000; then
               sudo kill -9 $(sudo lsof -t -i:4000) || true
            fi

            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/quiwe

            sudo docker compose up -d quiwe
